### ISSUE TITLE
Set up Python Discord for online chatting during the sprint.

### ISSUE THREAD

**Issue by Mariatta** [python/core-sprint#3]
Just use the hosted version instead of trying to set it up ourselves.

Python Discord can host the sprint on their server - easiest option 
Contacted Python Discord owners to confirm, they are 100% on-board with hosting it
Bot integration using Zapier

**Comment by Mariatta** [comment]
@aeros since you're familiar with Discord, can you take care of this task?

**Comment by aeros** [comment]
No problem! I just recently talked with the owners and admins of Python Discord.

The only thing that we need to do is figure out the channel layout (for the Sprint category, see https://github.com/python/core-sprint/issues/11), specify any additional roles needed, provide Discord usernames of the core devs participating, and then we should be ready as far as initial Discord setup goes. They already have an existing `CPython: Core Developer` role that can be used. I think it would also be good to have a `Python Sprint: Organizer` role (admin permissions within the Sprint category) and maybe a `Steering Council` role.

In the meantime, I'll have them create the category for the Sprint and provide me with permissions to make changes within it so we can add the channels as soon as we figure out the structure. I'll also be able to configure the permissions globally for the category, so that any channels created in the category will inherit those permissions. This should make it a bit easier for us to create channels as needed that will instantly have the permissions, instead of having to configure each one manually.

As for the Zapier bot integration, are we also looking to directly use Discord for it as well, such as automatically linking to open PRs in a specific text channel when the sprint label is added? Or is that entirely separate from Discord setup?

**Comment by aeros** [comment]
I've just recently created a [poll](https://discuss.python.org/t/2020-core-dev-sprint-poll-discord-or-zulip/5016) to determine which platform core developers prefer (Discord or Zulip). For now, this issue is blocked on the results of the poll, which will be available in 2 weeks from now (Sept. 2nd).

**Comment by ejodlowska** [comment]
The decision from the poll is to use a public Discord server. @aeros will with with the Python Discord community to set this up.

**Comment by aeros** [comment]
Update: the sprint category has been created, and I recently reached out to the folks at Python Discord about the permissions to set up Zapier integration.

**Comment by aeros** [comment]
It looks like all of the required permissions are good to go for the Zapier bot (on Python Discord). The last remaining step is running the script to mass-assign the participant role for the sprint (`Sprinter`). However, I'm waiting until we have most of the Discord usernames from participants (an [announcement](https://mail.python.org/archives/list/python-committers@python.org/thread/H3BFBA2HH5SQ222DL27YFI3ABKAONAKI/) was sent out on Oct. 2nd to collect usernames and get everyone on the Python Discord server).

So far, I've received around half of the Discord usernames of participants.

**Comment by aeros** [comment]
Still adding a few last-minute participants to Python Discord, but other than that, we're 100% good to go for online audio/video chatting during the sprint.
